name: Deploy ResolveMZ
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - run: CI=false npm run build
        env:
          REACT_APP_GROQ_API_KEY: ${{ secrets.REACT_APP_GROQ_API_KEY }}
      - name: Deploy
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add build -f
          git commit -m "Deploy ResolveMZ"
          git subtree push --prefix build origin gh-pages
